#pragma once
#include <cstdint>

enum TokenKind : uint32_t {
    TOKEN_EOF = 0,
    TOKEN_HASH,
    TOKEN_UNKNOWN,

    // Идентификаторы и литералы
    TOKEN_IDENTIFIER,
    TOKEN_NUMBER,
    TOKEN_STRING,
    TOKEN_CHAR,

    // Ключевые слова (добавим парочку для примера)
    TOKEN_KW_ALIGNAS,
    TOKEN_KW_ALIGNOF,
    TOKEN_KW_ASM,
    TOKEN_KW_ATOMIC_CANCEL,
    TOKEN_KW_ATOMIC_COMMIT,
    TOKEN_KW_ATOMIC_NOEXCEPT,
    TOKEN_KW_AUTO,
    TOKEN_KW_BOOL,
    TOKEN_KW_BREAK,
    TOKEN_KW_CASE,
    TOKEN_KW_CATCH,
    TOKEN_KW_CHAR,
    TOKEN_KW_CLASS,
    TOKEN_KW_CONCEPT,
    TOKEN_KW_CONST,
    TOKEN_KW_CONSTEVAL,
    TOKEN_KW_CONSTEXPR,
    TOKEN_KW_CONSTINIT,
    TOKEN_KW_CONST_CAST,
    TOKEN_KW_CONTINUE,
    TOKEN_KW_CONTRACT_ASSERT,
    TOKEN_KW_CO_AWAIT,
    TOKEN_KW_CO_RETURN,
    TOKEN_KW_CO_YIELD,
    TOKEN_KW_DECLTYPE,
    TOKEN_KW_DEFAULT,
    TOKEN_KW_DEFINE,
    TOKEN_KW_DEFINED,
    TOKEN_KW_DELETE,
    TOKEN_KW_DO,
    TOKEN_KW_DOUBLE,
    TOKEN_KW_DYNAMIC_CAST,
    TOKEN_KW_ELIF,
    TOKEN_KW_ELIFDEF,
    TOKEN_KW_ELIFNDEF,
    TOKEN_KW_ELSE,
    TOKEN_KW_ENDIF,
    TOKEN_KW_EMBED,
    TOKEN_KW_ENUM,
    TOKEN_KW_ERROR,
    TOKEN_KW_EXPLICIT,
    TOKEN_KW_EXPORT,
    TOKEN_KW_EXTERN,
    TOKEN_KW_FALSE,
    TOKEN_KW_FINAL,
    TOKEN_KW_FLOAT,
    TOKEN_KW_FOR,
    TOKEN_KW_FRIEND,
    TOKEN_KW_GOTO,
    TOKEN_KW_IF,
    TOKEN_KW_IFDEF,
    TOKEN_KW_IFNDEF,
    TOKEN_KW_IMPORT,
    TOKEN_KW_INCLUDE,
    TOKEN_KW_INLINE,
    TOKEN_KW_INT,
    TOKEN_KW_LONG,
    TOKEN_KW_LINE,
    TOKEN_KW_MODULE,
    TOKEN_KW_MUTABLE,
    TOKEN_KW_NAMESPACE,
    TOKEN_KW_NEW,
    TOKEN_KW_NOEXCEPT,
    TOKEN_KW_NULL,
    TOKEN_KW_OPERATOR,
    TOKEN_KW_OVERRIDE,
    TOKEN_KW_PRAGMA,
    TOKEN_KW_PRE,
    TOKEN_KW_PRIVATE,
    TOKEN_KW_PROTECTED,
    TOKEN_KW_POST,
    TOKEN_KW_PUBLIC,
    TOKEN_KW_REFLEXPR,
    TOKEN_KW_REINTERPRET,
    TOKEN_KW_REQUIRES,
    TOKEN_KW_RETURN,
    TOKEN_KW_SHORT,
    TOKEN_KW_SIGNED,
    TOKEN_KW_SIZEOF,
    TOKEN_KW_STATIC,
    TOKEN_KW_STATIC_ASSERT,
    TOKEN_KW_STATIC_CAST,
    TOKEN_KW_STRUCT,
    TOKEN_KW_SWITCH,
    TOKEN_KW_SYNCHRONIZED,
    TOKEN_KW_TEMPLATE,
    TOKEN_KW_THIS,
    TOKEN_KW_TREAD_LOCAL,
    TOKEN_KW_THROW,
    TOKEN_KW_TRUE,
    TOKEN_KW_TRY,
    TOKEN_KW_TYPEDEF,
    TOKEN_KW_TYPEID,
    TOKEN_KW_TYPENAME,
    TOKEN_KW_UNDEF,
    TOKEN_KW_UNION,
    TOKEN_KW_UNSIGNED,
    TOKEN_KW_USING,
    TOKEN_KW_VIRTUAL,
    TOKEN_KW_VOID,
    TOKEN_KW_VOLATILE,
    TOKEN_KW_WARNING,
    TOKEN_KW_WHILE,

    // Операторы
    TOKEN_PLUS, TOKEN_PLUS_PLUS, TOKEN_PLUS_EQUAL,       // + ++ +=
    TOKEN_MINUS, TOKEN_MINUS_MINUS, TOKEN_MINUS_EQUAL,   // - -- -=
    TOKEN_STAR, TOKEN_STAR_EQUAL,                        // * *=
    TOKEN_SLASH, TOKEN_SLASH_EQUAL,                      // / /=
    TOKEN_PERCENT, TOKEN_PERCENT_EQUAL,                  // % %=
    TOKEN_ASSIGN, TOKEN_EQUAL,                           // = ==
    TOKEN_NOT, TOKEN_NOT_EQUAL,                          // ! !=
    TOKEN_LESS, TOKEN_LESS_EQUAL, TOKEN_LSHIFT,          // < <= <<
    TOKEN_GREATER, TOKEN_GREATER_EQUAL, TOKEN_RSHIFT,    // > >= >>

    // Пунктуация
    TOKEN_LPAREN, TOKEN_RPAREN,                          // ( )
    TOKEN_LBRACE, TOKEN_RBRACE,                          // { }
    TOKEN_LBRACKET, TOKEN_RBRACKET,                      // [ ]
    TOKEN_SEMICOLON, TOKEN_COMMA, TOKEN_DOT,              // ; , .

    TOKEN_NEWLINE,
    TOKEN_SYSTEM_INCLUDE
};

struct Token {
    TokenKind kind;
    uint32_t string_id; // ID из StringPool (или 0)

    // Упакованные координаты (чтобы влезть в 16 байт)
    uint32_t line;
    uint32_t column;

    // Флаги (например: 1 - это float, 2 - hex, 3 - содержит ошибки)
    uint32_t flags;
};
